Repository laurolmer/Acme-L3-D02, pull requests merged in 2023-03, with the labels that each got.

#112 feat(std1): creada la entidad Lecture
  src/main/java/acme/entities/course/CourseLecture.java
  src/main/java/acme/entities/lecture/Lecture.java
  src/main/java/acme/entities/lecture/LectureType.java
Labels: enhancement

#116 feat(std1): creada la lecturerDashboard
  src/main/java/acme/form/LecturersDashboard.java
Labels: enhancement

#118 fix(std1): añadido el atributoderivado estimatedTotalTime
  src/main/java/acme/entities/course/Course.java
Labels: bug

#144 fix(sample):arreglo sample de lecture, course, course-lecture
  src/main/webapp/WEB-INF/resources/sample-data/courseLecture.csv
  src/main/webapp/WEB-INF/resources/sample-data/lecture.csv
Labels: bug, enhancement

#146 Grupal task 019
  reports/model.uxf
Labels: bug, documentation

#145 Fix followup1 albertoperleo
  src/main/java/acme/entities/course/Course.java
  src/main/webapp/WEB-INF/resources/sample-data/course.csv
Labels: bug, enhancement

#154 Grupal task 016
  src/main/webapp/WEB-INF/resources/sample-data/banner.csv
  src/main/webapp/WEB-INF/resources/sample-data/bulletin.csv
  src/main/webapp/WEB-INF/resources/sample-data/course.csv
  src/main/webapp/WEB-INF/resources/sample-data/note.csv
  src/main/webapp/WEB-INF/resources/sample-data/offer.csv
  src/main/webapp/WEB-INF/resources/sample-data/peep.csv
Labels: bug, documentation, enhancement

#160 feat(doc):analysis report albertoperleo
  reports/student #1/Analysis Report.pdf
Labels: documentation

#161 feat(doc):planning report
  reports/student #1/Planning Report.pdf
Labels: documentation

#163 Added -Task 010 danguepre
  reports/student #2/Planning Report-D01.pdf
  reports/student #2/Planning Report-D02.pdf
  reports/student #2/Requirements - Student #2.docm
Labels: documentation

#159 Fix followup2 albertoperleo
  reports/model.uxf
  reports/student #1/Analysis Report-D01.pdf
  reports/student #1/Analysis Report-D02.pdf
  reports/student #1/Planning Report-D01.pdf
  reports/student #1/Planning Report-D02.pdf
  src/main/java/acme/entities/course/Course.java
  src/main/java/acme/entities/course/CourseLecture.java
  src/main/java/acme/entities/lecture/Lecture.java
  src/main/webapp/WEB-INF/resources/sample-data/banner.csv
  src/main/webapp/WEB-INF/resources/sample-data/bulletin.csv
  src/main/webapp/WEB-INF/resources/sample-data/course.csv
  src/main/webapp/WEB-INF/resources/sample-data/courseLecture.csv
  src/main/webapp/WEB-INF/resources/sample-data/lecture.csv
  src/main/webapp/WEB-INF/resources/sample-data/note.csv
  src/main/webapp/WEB-INF/resources/sample-data/offer.csv
  src/main/webapp/WEB-INF/resources/sample-data/peep.csv
Labels: bug, enhancement
